### ISSUE TITLE
Colemak-DH incorrect key color placement

### ISSUE THREAD

**Issue by marvielb** [aradzie/keybr.com#112]
In the official [ANSI](https://colemakmods.github.io/mod-dh/keyboards.html#ansi-keyboards) layout of mod dh, the keys on the left side is angled like so:

![](https://colemakmods.github.io/mod-dh/gfx/about/colemak_dh_main_ansi.png)

The w,r,x keys are pressed by ring finger and f,s,c keys are pressed by middle etc.

But in keybr, it shows a non-angled version:

![image](https://github.com/aradzie/keybr.com/assets/50162243/32ef4c3e-c730-4ac4-9aab-2d007437a9f4)

**Comment by aasutossh** [comment]
Ohh, and i was learning to press d with my middle finger.

**Comment by aradzie** [comment]
I believe I have fixed the issue in 910d926cb1f1a273936ffaa4e843d2c4805b3451.

# Colemak
![colemak](https://github.com/aradzie/keybr.com/assets/44386/98ec7249-d118-4290-b5c2-6cfc647b6fa5)

# Colemak-DH (ANSI)

![colemak-dh-ansi](https://github.com/aradzie/keybr.com/assets/44386/fcbb8acc-3779-43fb-b665-be92f5e94e25)

# Colemak-DH Wide (ANSI)

![colemak-dh-ansi-wide](https://github.com/aradzie/keybr.com/assets/44386/1c5b0bce-e6b2-42e4-8393-35cb7396b8c0)

# Colemak-DH (ISO)

![colemak-dh-iso](https://github.com/aradzie/keybr.com/assets/44386/00372675-65f9-4636-9968-10fb5a44ded9)

# Colemak-DH Wide (ISO)

![colemak-dh-iso-wide](https://github.com/aradzie/keybr.com/assets/44386/f13a5b94-65f5-4515-b36e-1756e5094ddd)
