### ISSUE TITLE
Lower threshold for longer key combinations

### ISSUE THREAD

**Issue by artm** [aradzie/keybr.com#115]
I'm learning a custom small factor keyboard with some characters on separate layers requiring two key strokes to enter. This makes such characters harder to get to the same wpm as single key characters.

I would like to be able to upload some kind of "character weights" file to compensate for that. 

I think it is even more pronounced for the characters requiring use of dead keys or compose key. 

I feel like my goal is to train key strokes per minute, not words per minute. So characters requiring a modifier should "weigh" maybe 1.5 that of normal ones and characters requiring dead keys twice or more. 

The current method leads me to increased tension in anticipation of an expensive character.

**Comment by rplazevedo** [comment]
+1 This would be great for languages that have lots of diacritics. I've been stuck on ã for weeks in Portuguese trying to reach 35 wpm, while my average is in the high forties.
