### ISSUE TITLE
Text gets truncated at the bottom upon typing error (Safari)

### ISSUE THREAD

**Issue by deberle** [aradzie/keybr.com#119]
See image for details –the text gets truncated at the bottom upon typing error in Safari.

![Untitled](https://github.com/aradzie/keybr.com/assets/186417/69d3ba19-6d2a-4a05-b34c-5e9d7c48d068)

**Comment by aasutossh** [comment]
Same thing happens in Chrome Dev Version 123.0.6262.5 (Official Build) dev (64-bit).
