### ISSUE TITLE
feature: allow to resize and reposition the components on the practice screen

### ISSUE THREAD

**Issue by aradzie** [aradzie/keybr.com#12]
Use mouse wheel to zoom the virtual keyboard and the text fragment.
Add the ability to drag these components using mouse to a different location on the screen.

**Comment by andreasbruckmeier** [comment]
Hi @aradzie, does this feature address the problem I`m facing right now? I use keybr.com on a rather large 4k monitor and on each page reload, the UI is adapted to the screen size, not the actual size of the browser window. Using keybr on fullscreen is way to big but with a downsized browser, I see only half of the page.

**Comment by aradzie** [comment]
> Hi @aradzie, does this feature address the problem I`m facing right now? I use keybr.com on a rather large 4k monitor and on each page reload, the UI is adapted to the screen size, not the actual size of the browser window. Using keybr on fullscreen is way to big but with a downsized browser, I see only half of the page.

Yes, I can confirm, keybr is adapted for various screen sizes. 
Maybe you can mitigate your issue by using the built-in zoom capability of the modern browsers:

https://support.mozilla.org/en-US/kb/font-size-and-zoom-increase-size-of-web-pages
https://support.google.com/chrome/answer/96810?hl=en
