### ISSUE TITLE
Add engrammer layout

### ISSUE THREAD

**Issue by centy** [aradzie/keybr.com#158]
https://github.com/sunaku/engrammer

**Comment by aradzie** [comment]
I am afraid there is not much interest in the Engram layout.

I checked the github repository, the Engram project has 221 stars, and Engrammer has 63 stars.

However, the layout files are in the keybr repository:

[engram.klc](https://github.com/aradzie/keybr.com/blob/a429ac194c28f5d1597284023038b1ccaa4fc23a/packages/keybr-keyboard-generator/layout/engram.klc)
[engrammer.klc](https://github.com/aradzie/keybr.com/blob/a429ac194c28f5d1597284023038b1ccaa4fc23a/packages/keybr-keyboard-generator/layout/engrammer.klc)

If you are a programmer, maybe you can create your own build of keybr with these layouts included. It should not be too difficult, following the [instructions](https://github.com/aradzie/keybr.com/blob/master/docs/custom_keyboard.md).

**Comment by cole-h** [comment]
I was able to get it to work with the following diff:

```diff
diff --git a/packages/keybr-generators/layout/engrammer.klc b/packages/keybr-generators/layout/engrammer.klc
index e91508e..44c5cff 100644
Binary files a/packages/keybr-generators/layout/engrammer.klc and b/packages/keybr-generators/layout/engrammer.klc differ
diff --git a/packages/keybr-keyboard/lib/layout.ts b/packages/keybr-keyboard/lib/layout.ts
index bdc7dfb..230ae00 100644
--- a/packages/keybr-keyboard/lib/layout.ts
+++ b/packages/keybr-keyboard/lib/layout.ts
@@ -737,6 +737,17 @@ export class Layout implements XEnumItem {
       Geometry.MATRIX,
     ),
   );
+  static readonly EN_ENGRAMMER = new Layout(
+      /* id= */ "en-engrammer",
+      /* xid= */ 0xff,
+      /* name= */ "Engrammer",
+      /* family= */ "engrammer",
+      /* language= */ Language.EN,
+      /* emulate= */ true,
+      /* geometries= */ new Enum(
+        Geometry.MATRIX,
+      ),
+  );
 
   static readonly ALL = new XEnum<Layout>(
     Layout.EN_US,
@@ -789,6 +800,7 @@ export class Layout implements XEnumItem {
     Layout.AR_SA,
     Layout.AR_SA_102,
     Layout.FA_IR,
+    Layout.EN_ENGRAMMER,
   );
 
   static findLayout(localeId: string): Layout | null {
diff --git a/packages/keybr-keyboard/lib/layout/en_engrammer.ts b/packages/keybr-keyboard/lib/layout/en_engrammer.ts
index 909bac3..1fdfb3b 100644
--- a/packages/keybr-keyboard/lib/layout/en_engrammer.ts
+++ b/packages/keybr-keyboard/lib/layout/en_engrammer.ts
@@ -27,9 +27,9 @@ export const LAYOUT_EN_ENGRAMMER: CodePointDict = {
   KeyI: [/* d */ 0x0064, /* D */ 0x0044],
   KeyO: [/* w */ 0x0077, /* W */ 0x0057],
   KeyP: [/* v */ 0x0076, /* V */ 0x0056],
-  BracketLeft: [/* z */ 0x007a, /* Z */ 0x005a],
+  BracketLeft: [/* \ */ 0x005c, /* | */ 0x007c],
   BracketRight: [/* = */ 0x003d, /* + */ 0x002b],
-  Backslash: [/* \ */ 0x005c, /* | */ 0x007c],
+  Backslash: [/* z */ 0x007a, /* Z */ 0x005a],
   KeyA: [/* c */ 0x0063, /* C */ 0x0043],
   KeyS: [/* i */ 0x0069, /* I */ 0x0049],
   KeyD: [/* e */ 0x0065, /* E */ 0x0045],
diff --git a/packages/keybr-keyboard/lib/load.ts b/packages/keybr-keyboard/lib/load.ts
index 8bb7d9d..3591092 100644
--- a/packages/keybr-keyboard/lib/load.ts
+++ b/packages/keybr-keyboard/lib/load.ts
@@ -62,6 +62,7 @@ import { LAYOUT_SV_SE } from "./layout/sv_se.ts";
 import { LAYOUT_TR_TR_F } from "./layout/tr_tr_f.ts";
 import { LAYOUT_TR_TR_Q } from "./layout/tr_tr_q.ts";
 import { LAYOUT_UK_UA } from "./layout/uk_ua.ts";
+import { LAYOUT_EN_ENGRAMMER } from "./layout/en_engrammer.ts";
 import { KeyboardOptions } from "./settings.ts";
 import { type CodePointDict, type GeometryDict } from "./types.ts";
 
@@ -116,6 +117,7 @@ const layoutDict = new Map<Layout, CodePointDict>([
   [Layout.TR_TR_F, LAYOUT_TR_TR_F],
   [Layout.TR_TR_Q, LAYOUT_TR_TR_Q],
   [Layout.UK_UA, LAYOUT_UK_UA],
+  [Layout.EN_ENGRAMMER, LAYOUT_EN_ENGRAMMER],
 ]);
 
 const geometryDict = new Map<Geometry, GeometryDict>([

```

(I know the modification to `en_engrammer.ts` won't stick, I just wanted the graphic to line up -- mostly -- with the actual layout. I don't know why the KLC is "wrong", but I don't care to fix it right now.)

This in addition to following the getting started steps (https://github.com/aradzie/keybr.com/blob/master/docs/getting_started.md) got me up and running with a local keybr instance with Engrammer support!

Thanks a ton! Maybe this weekend I'll take a look at expanding the "adding a new layout" docs -- I was hitting weird errors until I added the layout to `packages/keybr-keyboard/lib/load.ts`, but otherwise the docs were pretty much what I needed to get going. Thanks for this project!

**Comment by aradzie** [comment]
> I don't know why the KLC is "wrong", but I don't care to fix it right now.)

I believe I took the definition of the Engrammer layout from the [official repository](https://github.com/sunaku/engrammer/blob/main/windows/engrammer.klc). If you want to eventually fix it, you are probably better to do it that repository and let me know about the change.

**Comment by aradzie** [comment]
> And somehow just copying the one from their repo over and regenerating resulted in an entirely empty (except for spacebar) layout!

It's probably because their files are encoded in UTF-16, but we read them as UTF-8. You can use the [dos2unix](https://linux.die.net/man/1/dos2unix) command to convert encoding and line endings. This words for me:

```sh
> dos2unix *.klc
```

**Comment by ocharles** [comment]
I use the Engrammer layout and would have liked this

**Comment by joefiorini** [comment]
I have been learning Engrammer for a couple months now and have an instance of keybr running locally using @cole-h diff posted above. It wasn't _too_ bad to get working, but I agree if someone has already done the work to get it working for real here it would be nice. Soundn like there might be work to do in the official repo though.

**Comment by axelson** [comment]
I'm also interested in this, I've started a PR on a fresh fork of keybr (since the PR isn't ready for the actual repo yet): https://github.com/axelson/keybr.com/pull/1
