### ISSUE TITLE
Add all keyboard layouts for each language

### ISSUE THREAD

**Issue by hadwll** [aradzie/keybr.com#166]
For persons that are learning a language it would be worthwhile to allow all keyboard layouts for each language.

 for example an English keyboard layout being able to be used on the German language would help an English speaker with their German writing skills.

It would be a bonus, and  this happens for people that are speaking more than one language.

**Comment by aradzie** [comment]
Done!

Now you can combine any Latin keyboard layout (Qwerty, Colemak, etc) with any Latin based language (English, German, etc).
