### ISSUE TITLE
Letters 'g' and 'q' are not clear when using Underlined Cursor

### ISSUE THREAD

**Issue by VSR-Adithya** [aradzie/keybr.com#167]
![image](https://github.com/aradzie/keybr.com/assets/98527498/fe08b1c0-7e93-4e56-8284-66246128bd33)
![image](https://github.com/aradzie/keybr.com/assets/98527498/8cf7fd8f-0a1a-40bd-8a16-255adfa9413b)

Letters 'g' and 'q' are not clear when using Underlined Cursor as shown in the attached pictures.

**Comment by aradzie** [comment]
As a workaround, I recently added to ability to change fonts.

![image](https://github.com/aradzie/keybr.com/assets/44386/49ff1f8b-1f0b-4856-a819-f261845268d5)

Maybe it will help until a proper fix.

A proper fix would probably be to use the [blend-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/blend-mode) feature to invert colors under the cursor.

**Comment by aradzie** [comment]
![image](https://github.com/aradzie/keybr.com/assets/44386/a6e24d5e-cbbb-4ddf-b301-14889653bf3b)
I think I have fixed it.

**Comment by aradzie** [comment]
I think I have fixed it.

![image](https://github.com/aradzie/keybr.com/assets/44386/acb3a22c-748f-457e-93cf-ef5b26b4c0bd)
