### ISSUE TITLE
[translation error] Error in Chinese translation

### ISSUE THREAD

**Issue by QuantumCipherMaster** [aradzie/keybr.com#182]
address: https://www.keybr.com/zh-hans/word-count
location: the last row 
The original English text: At the average reading speed of 300 WPM, it would take ** seconds to read this text.
The wrong Chinese translation: 以平均阅读速度300WPM，阅读从文本将要花费\**秒钟。
And it should be:以平均阅读速度300WPM，阅读此文本将要花费\**秒钟。
You should change “从” to “此”

从 means "from" in Chinese
此 means "this" in Chinese

**Comment by aradzie** [comment]
Thanks for letting me know!

You can contribute a fix yourself as is explained in the [docs](https://github.com/aradzie/keybr.com/blob/master/docs/translations.md), and it does not require coding. 

If not, that's ok, I'll fix it myself later.

**Comment by aradzie** [comment]
I saw that you already have fixed the translation. Thank you!
