### ISSUE TITLE
[Feature request] Allow mixing languages

### ISSUE THREAD

**Issue by g0r3** [aradzie/keybr.com#184]
Good day sir!

I am using keybr to learn touch typing right now and I find it pretty much awesome. One little feature I miss though is the mixing of languages and layouts. I am probably kinda more like a special case here, since I use a US layout even tough I am a german speaker. But I guess the need of typing english plus a different mother tongue is a very wide spread phenomenon.

Right now you cannot mix the typing word vocabularies of two languages to practice them at the same time. Also in the settings it seems not possible to use a language without a matching keyboard layout. So for example if I want to learn tying with the german vocabulary, I have to pick german as a language - makes sense. But at the same time I have to switch to a german keyboard layout, which for me as a US keyboard user makes no sense.

So my dream setup would be to practice typing with a mixed german and english vocabulary while sticking with the US keyboard layout. Would be super, if that would be possible at some point in the future. In the mean time I enjoy it like it is. Thanks! :)

**Comment by SortedShuffle** [comment]
Hello from Switzerand! 

Thank you for making your awesome project free open source. 
Similarity to @g0r3 here in Switzerland we often write in at least 3 different languages: german, french, italian and english for international communication. 
It would be great that the language you want to train is not bounded with the keyboard layout. 

It would be fantastic if this could be possible in the future, but for now, I’m enjoying it just as it is. Thank you for your amazing project!

**Comment by aradzie** [comment]
Done!

Now you can combine any Latin keyboard layout (Qwerty, Colemak, etc) with any Latin based language (English, German, etc).

**Comment by SortedShuffle** [comment]
Thank you very much :)
