### ISSUE TITLE
ü is broken

### ISSUE THREAD

**Issue by Omaeda** [aradzie/keybr.com#188]
![image](https://github.com/aradzie/keybr.com/assets/51844985/76cbd3ea-b4f2-41b0-9129-4d9b1d4e97c9)

**Comment by aradzie** [comment]
Hey, what language is that?

**Comment by Omaeda** [comment]
spanish

**Comment by aradzie** [comment]
From the messages on the user interface I assume it's the Spanish language. 

Would it be a good idea to completely remove the letter ü?

In our dictionary there are only a few words with that letter:

1. vergüenza 
2. antigüedad
3. avergüenza
4. sinvergüenza
5. antigüedades
6. averigüe

As a result, we cannot generate a good list of words with this letter.

In such a case I usually just remove a rare letter.
