### ISSUE TITLE
Add programming language to practice small programs

### ISSUE THREAD

**Issue by JakeWalker23** [aradzie/keybr.com#192]
[ENHANCEMENT]

Hi, just a suggestion but it would be good if there was an option to type programming language syntax aswell as random words. 

Perhaps you could upload a file and then type out its contents.

E.g python -> 
def printString(string):
     return hello + string

etc etc. 

Would make it more fun and programmer related. Just a suggestion, feel free to close if its not the path you want to take.

**Comment by JakeWalker23** [comment]
Sorry, you already have a snippet of this feature which is great! Maybe support could be added for some other languages, aswell as the ability to upload your own small program (or perhaps copy it).

Whilst not plain text, there is the workaround of copying your code into the plain text section and writing it out that way.

Again, feel free to close if you don't see this.

**Comment by aradzie** [comment]
I am not quite sure I follow. 

There is already an option to type custom text:

![image](https://github.com/aradzie/keybr.com/assets/44386/47266cc6-2e74-479f-88be-1e933546a90e)

Is this what you are looking for?

**Comment by JakeWalker23** [comment]
Pretty much, yes. I'll close this.
