### ISSUE TITLE
Unable to select options

### ISSUE THREAD

**Issue by GhostShadow0316** [aradzie/keybr.com#195]
I'm using Brave as my browser
a video tells anything:

https://github.com/aradzie/keybr.com/assets/94322065/842270a8-4324-4445-bd25-7ea3d4e4e9ae

I tried use Firefox and it works fine on it

**Comment by aradzie** [comment]
I'll take a look.

**Comment by aradzie** [comment]
So I tested in the most recent Brave on Windows and Linux, and could not reproduce this bug. If this is on MacOS, I am sorry, I don't have an Apple laptop at the moment to test it.

**Comment by GhostShadow0316** [comment]
I'm using Brave Nightly on Windows 10
![brave_Dc1o7JRsga](https://github.com/aradzie/keybr.com/assets/94322065/59d0f58b-91e3-4003-99f1-148367272a5d)

**Comment by aradzie** [comment]
I am sorry but I cannot reproduce this bug.

Here I successfully change options:

![image](https://github.com/aradzie/keybr.com/assets/44386/7a3c04bb-8f3c-4353-99ed-d40a330c60af)

It's brave nightly as well:

![image](https://github.com/aradzie/keybr.com/assets/44386/f4dde735-427b-4e7c-b315-91f31388c380)

**Comment by aradzie** [comment]
Try using your keyboard to change the options:

- Space key opens the drop down
- Arrow keys navigate between items
- Enter key selects an item
-

**Comment by GhostShadow0316** [comment]
well it worked
I have no idea what's going on
it's most likely my problem
still thanks for your help

**Comment by dtreskov** [comment]
I got same issue with drop down menus(Chrome browser, Windows 10. Via Firefox everything is OK), selecting with keyboard works well. Disabling uBlock and VPN doesnt work, clearing cookies too.
Maybe this can help to catch problem. Chrome generates next issue on attempt to change value in drop menu via mouse:
![Screenshot 2024-08-19 175750](https://github.com/user-attachments/assets/31520a2d-08bd-499b-ba28-6092beb96350)

I don't have any experience with DevTools, so i don't know which information can be useful for ya. If you need something else - i glad to help.

PS. Tested incognito tab in chrome - infinite loading as result. Tested Brave - it works fine for me.
