### ISSUE TITLE
Add Standard Persian Keyboard

### ISSUE THREAD

**Issue by javadzarezadeh** [aradzie/keybr.com#199]
The Persian keyboard on the website is from an old standard. Please add the new standard ISIRI 9147. The layout is described in this [PDF](https://persian-computing.org/references/ISIRI/ISIRI-9147.pdf). Moreover [this](http://persian-computing.org/download/Iranian_Standard_Persian_Keyboard_(ISIRI_9147)_(Version_2.0).zip) is the standard keyboard for Windows (Linux, Mac, and even the latest Windows versions use this new standard by default). I'm not familiar with the CLDR project, but since the keyboard is standard it should be available there.

**Comment by aradzie** [comment]
I believe you want [Persian Standard](http://kbdlayout.info/kbdfar) instead of [Persian](http://kbdlayout.info/kbdfa). Should we keep the latter, or it is obsolete and can be removed?

**Comment by javadzarezadeh** [comment]
Yes, it is deprecated but it is still available on Windows and there might be some people using the old one. I assume that keeping it might be beneficial for them. In my opinion, it is better to make the Persian Standard the default one, and the Legacy one as an option, but it is completely up to you.

**Comment by aradzie** [comment]
Now, how should we name these two layouts? Can you please provide native (Persian) names of these? It's the last step, then I'll add the standard layout as you requested.

**Comment by javadzarezadeh** [comment]
I believe "Persian - Standard" and "Persian - Legacy" are suitable. This naming is used on MacOS.

**Comment by javadzarezadeh** [comment]
Thanks a lot. It seems alright. I truly appreciate your prompt update!
