### ISSUE TITLE
feature: show state of the modifier keys, such as CapsLock and NumLock

### ISSUE THREAD

**Issue by aradzie** [aradzie/keybr.com#2]
On the virtual keyboard show state whether CapsLock and NumLock is on or off.

**Comment by j10ccc** [comment]
There are some compatible problems should be fixed before implement this feature.

Different browser handle key up&down event varies. When you press and release the CapsLock key firstly, Chrome only trigger a `onkeydown` event, while firefox trigger both `onkeydown` and `onkeyup` event. And Chrome handle NumLock as a normal key. 

A solution is here [[keyDown event is not fired for Capslock in Mac](https://stackoverflow.com/questions/39016292/keydown-event-is-not-fired-for-capslock-in-mac)](https://stackoverflow.com/questions/39016292/keydown-event-is-not-fired-for-capslock-in-mac)

**Comment by j10ccc** [comment]
Could you assign this to me, I believe I am capable for this.😁

**Comment by aradzie** [comment]
> There is a compatible problem should be fixed before implementing this feature.
> 
> Different browsers handle key up&down event vary. When you press and release the CapsLock key firstly, Chrome only triggers a `onkeydown` event, while firefox triggers both `onkeydown` and `onkeyup` events. And Chrome handles NumLock as a normal key.
> 
> A solution is here. [keyDown event is not fired for Capslock in Mac](https://stackoverflow.com/questions/39016292/keydown-event-is-not-fired-for-capslock-in-mac)

Well maybe not all hope is lost. I've test it myself with Chrome and Firefox, in Windows and Linux. Every combination worked as expected. 

![image](https://github.com/aradzie/keybr.com/assets/44386/7e4baa17-2668-4a5f-b24a-e23596904460)

Try it yourself: https://w3c.github.io/uievents/tools/key-event-viewer.html
