### ISSUE TITLE
[Feature] Add average accuracy to "All Time Statistics" and "Statistics for Today" on the profile page

### ISSUE THREAD

**Issue by madXmd** [aradzie/keybr.com#20]
Being accurate is a critical aspect to consider. While some may argue that it's more significant than speed, we can only measure our attempt accuracy and not the statistical trends like speed. Therefore, it is recommended to include the average accuracy in both the "All Time Statistics" and "Statistics for Today" sections on the profile page, just like speed.

**Comment by aradzie** [comment]
Done in the most recent update.
