### ISSUE TITLE
Word Count doesn't work for Arabic

### ISSUE THREAD

**Issue by AA0000-33** [aradzie/keybr.com#202]
![image](https://github.com/aradzie/keybr.com/assets/22997509/6c684b0b-5382-4fa0-94e8-61e244722afd)

It's only calculating the English text, it's not calculating the Arabic text.

**Comment by aradzie** [comment]
Thanks for letting me know.
I guess I have to use the [Intl.Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) class. It's a recent API, but a polyfill must be available for older browsers/
