### ISSUE TITLE
BUG: Diacritics not included in custom text mode

### ISSUE THREAD

**Issue by YeapGuy** [aradzie/keybr.com#212]
When I enter a text with diacritics, such as č, š, é etc. in custom text mode, the characters are not included in the practice text.
I want to practice typing these special characters.

To reproduce:
![image](https://github.com/aradzie/keybr.com/assets/43749899/889674ad-9e2c-48d8-8422-0e10118f14dd)
```
Dekameron je cyklus 100 noviel talianskeho autora Giovanniho Boccaccia, ktoré napísal v rokoch 1349 až 1353. 100 noviel je rozdelených podľa príbehov desiatich ľudí na desať dní. Je to základajúce dielo žánru renesančnej novely. Prvenstvo má tiež čo sa týka jazyka, v ktorom je napísané: novely boli napísané v novodobom talianskom jazyku v období, keď sa ešte používala latinčina.
[...]
```
![image](https://github.com/aradzie/keybr.com/assets/43749899/7bcf8b8f-c54b-49fa-9a51-063178491254)

**Comment by aradzie** [comment]
It's probably because these characters are missing you your keyboard layout. Try using the native layout for your language. Does it help?

Although a better behavior would be to remove the diactritics, `č` -> `c`.
