### ISSUE TITLE
Feature: Ignore space character errors in source code lessons

### ISSUE THREAD

**Issue by DevTGhosh** [aradzie/keybr.com#218]
Hey usually in an IDE we have code formatting setup that fixes formatting errors with spaces between variables. So adding or removing spaces should not count as errors. 

I don't think this should be a valid error in the lessons. 
![CleanShot 2024-05-16 at 19 17 27](https://github.com/aradzie/keybr.com/assets/25743418/3eaa896d-b54a-49e2-a5fb-bfca507df1bc)

**Comment by aradzie** [comment]
That's a good idea.
