### ISSUE TITLE
Issue with UI Daily Goal percentage

### ISSUE THREAD

**Issue by dsinkey** [aradzie/keybr.com#219]
Right now the UI is showing that I have completed almost 17,000% of my daily goal

![Screen Shot 2024-05-17 at 8 31 59 AM](https://github.com/aradzie/keybr.com/assets/7810819/297e109f-d096-4dca-8d86-f0c5c355485e)

**Comment by aradzie** [comment]
Ah, yes, an untested buggy update. I have reverted it.
