### ISSUE TITLE
Unlock a next key only when the previous keys are also above the target speed broken

### ISSUE THREAD

**Issue by carelvniekerk** [aradzie/keybr.com#228]
Unlock a next key only when the previous keys are also above the target speed feature broken by latest commit "feat: cling to the unlocked key" This feature seems to have been nullified by this commit.

**Comment by aradzie** [comment]
But I think I tested it thoroughly. I wrote a lot of unit tests to better understand the new change. I also manually went through the keys to see it with my eyes.

Can you please elaborate what's wrong with the new change? It should behave as follows:

1. When you unlock a new key, focus stays on this key until you reach the target speed. Focus never shifts to any other key.
2. When you finally reach the target speed, two outcomes are possible:
2.1. If *Unlock a next key only when...* is disabled, then a new key is unlocked and focused.
2.2. If *Unlock a next key only when...* is enabled, then the focus shifts to a previous key with the least typing speed. 
2.2.1. Once you reach the target speed for all the current keys again, then a new key is unlocked.

**Comment by dsinkey** [comment]
I've noticed a change as well. The number of unlocked keys went down. I had an additional 5-6 keys that were unlocked before the update.

![Screen Shot 2024-05-28 at 9 44 55 AM](https://github.com/aradzie/keybr.com/assets/7810819/939dd8cf-409d-42bd-8c64-6024e735b5e3)
![Screen Shot 2024-05-28 at 9 45 12 AM](https://github.com/aradzie/keybr.com/assets/7810819/80a8cf73-0071-426d-bdce-967e6b0936e6)

**Comment by aradzie** [comment]
I have reverted the recent changes. Things should go back to where they were before.
