### ISSUE TITLE
Bug: "¿" doesn't work anymore

### ISSUE THREAD

**Issue by DavidDOG4** [aradzie/keybr.com#237]
I practice my typing skills in spanish, however like a week ago every time i face the upsidedown question mark "¿" and press the correct key for it, it takes it as wrong, but when i use the normal question mark "?" instead it takes it as correct, it used to work perfectly fine a week or two ago.

**Comment by DavidDOG4** [comment]
The same thing happens with "¡" and "!", it suggests the write key, but takes it as wrong.

**Comment by monterrubio** [comment]
Same here, have tried all combinations of options on the layout settings. The on screen keyboard show the correct key pressed but it does not register. Can we have an estimation of the time to resolve this issue? as it is right now, I cannot use the application and I have paid for the premium account. If is not resolved I would have to ask for a refund. Thanks in advance
