### ISSUE TITLE
Feature request:  Add "Graphite" Keyboard Layout

### ISSUE THREAD

**Issue by MagicalAlchemist** [aradzie/keybr.com#240]
https://github.com/rdavison/graphite-layout
https://cyanophage.github.io/#graphite

recommended alternative keyboard layout from several reddit users.

**Comment by aradzie** [comment]
They don't seem to have a machine readable (like JSON) layout definition file, so I had to make my own definition by visual inspection. I looked at the layout picture and updated the definition. I hope I did not do any mistakes.

**Comment by MagicalAlchemist** [comment]
Thank you very much for your hardwork. Didn't expect to get a quick response.

**Comment by MagicalAlchemist** [comment]
@aradzie Only Graphite can't simulate the layout to physical keyboard. What I type follows the layout i used on my computer. But with other layout option, every layout option can simulate without any issues.

**Comment by aradzie** [comment]
Ah, right. The fix is [trivial](d872b610a82bf44e8a6a712575e7f49e0fef1f17). I've update the web site with the fix.
