### ISSUE TITLE
Feature Request: System Theme

### ISSUE THREAD

**Issue by UnifeGi** [aradzie/keybr.com#246]
I would like a theme that's automatic to system theme, like if the system theme is light, should switch to the light theme on the website. if dark, then switch to the dark theme.

I think there should be a toggle in the "settings", if you want system theme enabled or not. or similarly, a project like [PairDrop](https://github.com/schlagmichdoch/pairdrop), they have a system theme on by default, but wait, when you hover to the icon at the top right, it goes to three options, adapt to system theme, always light and dark themes. if that's possible... 🚀

since I have an automatic timer to when system theme goes to light or dark, I would definitely want this feature implemented.
I wish I could do a pull request and implement the feature, but I don't have any experience in coding... 😕

thank you so much for reading, and a website for touch typing properly! ⭐

**Comment by aradzie** [comment]
I hope to get this done soon.

**Comment by aradzie** [comment]
![image](https://github.com/user-attachments/assets/d99a075c-3410-43e6-b24a-2a8ed67ad3d4)
Done.
Chose the `System` theme to sync with your system preferences.
