### ISSUE TITLE
Method breaking characters for spanish language

### ISSUE THREAD

**Issue by monterrubio** [aradzie/keybr.com#253]
Hi, there is already an issue about this, but lookin at the code I see that the method basicPuntuation is changing the codes for the several characters  (including "¡" and "¿") that are used as punctuation in spanish language. 
https://github.com/aradzie/keybr.com/blob/f05c2f71255e8fe3c80f552e9deed9167b495125/packages/keybr-keyboard/lib/filter.ts#L561

Please, remove this method or at least apply for non-spanish languages.
Thanks

**Comment by monterrubio** [comment]
Already made a pull request to fix the issue [https://github.com/aradzie/keybr.com/pull/254](https://github.com/aradzie/keybr.com/pull/254)

**Comment by aradzie** [comment]
We have fixed this issue.
