### ISSUE TITLE
The word "sexual" is coming up twice per practice.

### ISSUE THREAD

**Issue by neinja007** [aradzie/keybr.com#263]
I am typing with this amazing website, and I absolutely love it. The issue is that the word *sexual* comes up **veeery** often, which I noticed as I was practising the letter "x".

Personally I don't care that much, but perhaps other, younger people would not love this.

**Comment by Jakeroid** [comment]
What do you suggest? I don't quite understand what words are "good" and what aren't.

**Comment by neinja007** [comment]
I did not use the word "good". What I thought I explained in sufficient detail is that said word may be inappropriate for minors, especially considering that, as far as I am aware, there are no warnings or "please enter your age" prompts.

Possible alternatives may include box, boxer, axe, xenon, pickaxe, vex, and fox.

**Comment by matey-jack** [comment]
Expunge extraneous sexuality in texts, except extramarital.

There are really not so many words with x and it's important to practice common words. Image the embarrassment when a teen texts their friend "let's have sez".

**Comment by kshuxx** [comment]
The issue has been successfully resolved. All related changes have been integrated into the main branch. 

Please review the updates at your convenience, and if everything looks good, kindly proceed to close this issue. 

Thank you @aradzie

**Comment by aradzie** [comment]
> The issue has been successfully resolved. All related changes have been integrated into the main branch.
> 
> Please review the updates at your convenience, and if everything looks good, kindly proceed to close this issue.
> 
> Thank you @aradzie

Oh, not so fast :(

You see, the list of words that you fixed is generated from another source. The next time I update the languages this word list will be regenerated and your changes will be lost.

I have a separate repository with the tools and scripts for scanning text corpora -- https://github.com/aradzie/keybr.com-corpus/tree/master/lang-en The excluded words must be configured in that repository, then the corpora must be re-scanned. This will take some time. However, I'll try to do this ASAP, and then I'll close this issue. In the mean time, I will keep your changes as a temporary workaround.

**Comment by nukdokplex** [comment]
what are you talking about, that's a usual word, like other ones in set
