### ISSUE TITLE
Ergo-L layout emulation does not work

### ISSUE THREAD

**Issue by jocelynthode** [aradzie/keybr.com#264]
Hey, not sure If I'm doing something wrong, but when emulating the Ergo-L layout I cannot type any key. I can see them being correctly pressed on the layout indicator but the cursor does not move.

Emulating any other layout works fine.

**Comment by aradzie** [comment]
The Ego-L layout has combining diacritic characters (Dead keys). We don't emulate such layouts, because it's a bit difficult to do so properly.
Maybe in the future we'll start emulating such layouts, then it will also work for Ergo-L.
