### ISSUE TITLE
Allow English words with German layout

### ISSUE THREAD

**Issue by FabianHertwig** [aradzie/keybr.com#28]
Currently if you select the English language in the settings, then you can only select the US and UK layouts. I would like to practice writing in English with my German keyboard though. So it would be great if the language and keyboard setting would be independent of each other.

**Comment by sbougrine** [comment]
I also think this would be a great addition. I think (speculation from my side with no eivdence to back it up) many people using different keyboard layouts would like to practice typing in English (in our case here, the german layout).

**Comment by eikowagenknecht** [comment]
It also goes the other way around. In addition to learning to properly type English on my US Colemak layout, I would also like to practice German with it.

**Comment by Sigmanificient** [comment]
yes, this is definitively needed

**Comment by behrends** [comment]
I would also use this feature to practice German on my English International keyboard.

**Comment by illiewillie** [comment]
Hi, I would also like to type English words using my country's keyboard which has the French/Belgian Azerty layout.
Many people that use AZERTY don't speak or write French.

**Comment by aradzie** [comment]
Done!

Now you can combine any Latin keyboard layout (Qwerty, Colemak, etc) with any Latin based language (English, German, etc).
