### ISSUE TITLE
Synchronize dark mode preference with browser

### ISSUE THREAD

**Issue by l0drex** [aradzie/keybr.com#281]
I am switching between light and dark mode based on the time of day. Therefore, I frequently manually change the dark mode in keybr.
It would be great if keybr could do that automatically instead, by **synching the setting with the preference reported by the browser**. This can be done through [css](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) or [javascript](https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript). There are also hooks for [react](https://www.npmjs.com/package/use-prefers-color-scheme).

I think I could do a PR for this, but the repo is quite big, and I have no idea where to start.

**Comment by UnifeGi** [comment]
I also made the same issue talking about it, #246.

**Comment by aradzie** [comment]
I am working on adding more themes. Along the way I want to update the theme switcher to add this feature.

**Comment by l0drex** [comment]
That sounds great!

**Comment by aradzie** [comment]
![image](https://github.com/user-attachments/assets/02bc2daf-7765-4c50-9f22-e6494ba3f11b)

Done. 
Chose the System theme from the menu to sync colors with your system preferences.
