### ISSUE TITLE
Colorblind Layout

### ISSUE THREAD

**Issue by Zo-Bro-23** [aradzie/keybr.com#282]
I'm colorblind (protan), and the keyboard color zones are slightly annoying. Dark mode makes it better, but changing the colors slightly or having an option for colorblindness would be great!

**Comment by Roger-Chavez** [comment]
Hi @Zo-Bro-23,

I’d love to help out around here over the next few weeks, and I’m particularly interested in working on color modes for people with visual impairments. I’m still in the early stages of learning about this, so as I do my research, could you point me to any resources on effective color schemes? If you know of any websites that have implemented good solutions, I’d really appreciate seeing a few examples that you and the community like. Thanks so much!

**Comment by aradzie** [comment]
I have added a way to use custom colors on the website. From the theme menu select "Custom". This will open a theme design dialog. There you will be able to change page colors, upload a custom background image, etc. There is also a way to change the keyboard zone colors.

![image](https://github.com/user-attachments/assets/c7d5eccd-f170-4c54-8c43-584cc6113b8c)

I think this is a good workaround for this issue, so let me close it as fixed.
