### ISSUE TITLE
Error In Settings of Typing-Test Page

### ISSUE THREAD

**Issue by zachOS-tech** [aradzie/keybr.com#284]
When I navigate to the Typing Test page, click on settings, and then go to the Typing tab, I get the following error message:
> Error
> 
> Oh no, something bad has happened!
> 
> Error
> Error
>     at Q (https://www.keybr.com/assets/00ac1a4012661017.js:1:103828)
>     at ie (https://www.keybr.com/assets/31c689b2173249cf.js:1:13051)
>     at gi (https://www.keybr.com/assets/cfc4c50c50229124.js:2:154981)
>     at ku (https://www.keybr.com/assets/cfc4c50c50229124.js:2:213950)
>     at bs (https://www.keybr.com/assets/cfc4c50c50229124.js:2:203198)
>     at ys (https://www.keybr.com/assets/cfc4c50c50229124.js:2:203126)
>     at gs (https://www.keybr.com/assets/cfc4c50c50229124.js:2:202989)
>     at os (https://www.keybr.com/assets/cfc4c50c50229124.js:2:199824)
>     at us (https://www.keybr.com/assets/cfc4c50c50229124.js:2:200206)
>     at ja (https://www.keybr.com/assets/cfc4c50c50229124.js:2:141355)

I have tried this on Firefox, Brave, and Edge and get the exact same error each time. This happens every time I navigate to the Typing tab in Settings.

In the developer tools, the top of the stack trace appears to be referencing `packages/keybr-keyboard/lib/context.tsx:12:11` where the `KeyboardContext` appears to be null: 

> console.js:288 Error
    at Q (context.tsx:12:11)
    at ie (TypingSettings.tsx:71:20)
    at gi (react-dom.production.min.js:160:137)
    at ku (react-dom.production.min.js:289:337)
    at bs (react-dom.production.min.js:279:389)
    at ys (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at os (react-dom.production.min.js:270:88)
    at us (react-dom.production.min.js:272:300)
    at ja (react-dom.production.min.js:127:105)

## Screenshot of error
![image](https://github.com/user-attachments/assets/afb699c6-79ca-4919-93a5-34917be8f9a3)

**Comment by aradzie** [comment]
Oh, I see. Thanks for letting me know. It's actually awesome that you debugged the error yourself and provided me with the details! I'll try to fix it asap.

**Comment by aradzie** [comment]
I have updated the website with the fix. Again, thanks for reporting the bug!

**Comment by zachOS-tech** [comment]
Perfect! I can verify that this is working now for me. 

Thank you for the quick resolution!
