### ISSUE TITLE
Feature Request: Add accuracy ranking to Typing Test

### ISSUE THREAD

**Issue by MichaelMrt** [aradzie/keybr.com#286]
It would be nice to have an accuracy comparison similar to the typing speed after a Typing Test:
_Faster than 63.3% of all other people. You are in the top 36.7%._

something like
_"Your accuracy is higher than 82.5% of all other people. You are in the top 17.5% for precision."_

**Comment by aradzie** [comment]
![image](https://github.com/user-attachments/assets/8bbeaf5b-fdb4-469e-b0e5-f802fce7aca5)
I really like the idea (I have an unhealthy obsession with graphs), and I've got a working prototype. I hope to finish this feature in the following few days.

**Comment by MichaelMrt** [comment]
Nice thanks😄
I am already curious to see my ranking.


I also have a follow-up idea.
Combine **accuracy** and **speed** to get a **score**.

The simplest way would probably be:
`accuracy[%] * speed[keys_pressed]`
or something like
`(accuracy[%] * speed[%]) / 2)`

Adding weights would be a nice way to balance things out. For example punish accuracy harder.

**Comment by ColdCactus** [comment]
Possibly, the same logic could be integrated into the WPM/CPM flyout menu and graph that appears when hovering over the individual unlocked letters?

The database may likely not contain the data yet, but eventually a joint distribution of speed/accuracy for the statistics to compare against would be wonderful! Until then, giving the "better than x% and more accurate than y% from separate statistics is more than plenty.

New users may also benefit from a brief note/guidance on focusing on speed or accuracy, depending on where they are in their learning path. 
After I finally unlocked all letters, I googled around on /r/typing to find the (helpful, for me) advice of focusing primarily on accuracy over speed and speed would follow. At the same time, avoiding perfection is important, or some people may get unreasonably hung up on individual mistakes.

**Comment by aradzie** [comment]
![image](https://github.com/user-attachments/assets/6691fde0-f309-43b8-90cc-671c4bc8e037)
Enjoy your accuracy rankings!

**Comment by aradzie** [comment]
> Possibly, the same logic could be integrated into the WPM/CPM flyout menu and graph that appears when hovering over the individual unlocked letters?
> 
> The database may likely not contain the data yet, but eventually, computing the score from the joint distribution of speed/accuracy for the statistics to compare against would be wonderful! Until then, giving the "better than x% and more accurate than y% from separate statistics (and as a score like you suggested) is more than plenty.
> 
> New users may also benefit from a brief note/guidance on focusing on speed or accuracy, depending on where they are in their learning path. After I finally unlocked all letters, I googled around on /r/typing to find the (helpful, for me) advice of focusing primarily on accuracy over speed and speed would follow. At the same time, avoiding perfection is important, or some people may get unreasonably hung up on individual mistakes.

Are you suggesting to overlay an accuracy graph over the speed graph in this popup window?

![image](https://github.com/user-attachments/assets/67c1d016-318f-40e0-a848-4f6688991f5a)

I think we can do this. As far as I remember (lol), we keep the number of errors for each individual letter, so this seems to be doable.

**Comment by aradzie** [comment]
> Nice thanks😄 I am already curious to see my ranking.
> 
> I also have a follow-up idea. Combine **accuracy** and **speed** to get a **score**.
> 
> The simplest way would probably be: `accuracy[%] * speed[keys_pressed]` or something like `(accuracy[%] * speed[%]) / 2)`
> 
> Adding weights would be a nice way to balance things out. For example punish accuracy harder.

@MichaelMrt This is how we compute scores for the high scores table

```
score = ((speed * complexity) / (errors + 1)) * (length / 50)
```

where `speed` is in chars per minute, complexity is the number of different characters used (the alphabet size, we reward for the variety of letters), `errors` is the numbers of errors, and `length` is the length of a text fragment (it should be not shorter than 50 characters).

A similar (or identical) scoring system can be added to the typing test. I have quite a few new features planned, this could be one of them.

**Comment by MichaelMrt** [comment]
> > Nice thanks😄 I am already curious to see my ranking.
> 
> > 
> 
> > I also have a follow-up idea. Combine **accuracy** and **speed** to get a **score**.
> 
> > 
> 
> > The simplest way would probably be: `accuracy[%] * speed[keys_pressed]` or something like `(accuracy[%] * speed[%]) / 2)`
> 
> > 
> 
> > Adding weights would be a nice way to balance things out. For example punish accuracy harder.
> 
> 
> 
> @MichaelMrt This is how we compute scores for the high scores table
> 
> 
> 
> ```
> 
> score = ((speed * complexity) / (errors + 1)) * (length / 50)
> 
> ```
> 
> 
> 
> where `speed` is in chars per minute, `complexity` is the number of different characters used (the alphabet size, we reward for the variety of letters), `errors` is the numbers of errors, and `length` is the length of a text fragment (it should be not shorter than 50 characters).
> 
> 
> 
> A similar (or identical) scoring system can be added to the typing test. I have quite a few new features planned, this could be one of them.
> 
> 
> 
> 
> 
> 
> 
> 

Thank you for explaining the score system and your hard work.

**Comment by ColdCactus** [comment]
> @ColdCactus, Are you suggesting to overlay an accuracy graph over the speed graph in this popup window?

Yes, pretty much! :)
Like the graph that exists on the stats page (for overall accuracy), just letter-specific. :)

**Comment by ColdCactus** [comment]
> Your all time average accuracy beats 76.07% of all other people

Huzzah! Accuracy rankings! Thank you!! 🤗 (Only now had time to practice again, after traveling for work this week..).

And I'm not sure whether I am happy for my result or slightly surprised (and scared) about everyone else. But, I suppose, people who are happy with their typing speed and accuracy are less likely to use the site and raise the bar to begin with so it makes sense from a self-selecting sampling perspective. 🤔
