### ISSUE TITLE
Reduced contrast

### ISSUE THREAD

**Issue by lucaben** [aradzie/keybr.com#290]
It looks like about 10 minutes ago, as I was practicing, suddenly the colour of the typed-in text has changed. I find the new colour combination confusing, before it was more obvious what text had been typed in and what text still had to be typed, now it's not so obvious. I would revert back to the original. Cheers

**Comment by rplazevedo** [comment]
I too think the new dark theme especially has worse contrast than the old one. Especially on the green tones of the  letters at the top as you improve. I think they were lighter before, which also worked better with black letters inside

**Comment by aradzie** [comment]
I am receiving mixed opinions on this one.
Some people want a darker theme, some want a lighter one.
Unfortunately, we cannot please everyone :(
However, now you can create your own themes!
From the theme menu select "Custom". This will open a theme designer. There you will be able to adjust colors to your liking, upload your own background image, etc.

![image](https://github.com/user-attachments/assets/0133498f-209d-48be-87a5-3f857f7dd94d)

This feature is a work in progress. There are a few known bugs and missing features. I hope to fix these in the coming days.
