### ISSUE TITLE
scoring

### ISSUE THREAD

**Issue by owenpaulmeyer** [aradzie/keybr.com#305]
as a daily user of keybr i have noticed an issue with the scoring. when i am working on passing the 'current key' i can get my wpm for said key to go up simply by rapid/haphazard peppering of keys. my wpm goes way down except for the 'current key' which rapidly increases. i can always get the current key to pass the current wpm setting by using this hack.

**Comment by Finnitio** [comment]
I don't get the system either. Atm I am learning a new layout and hit 22 wpm in a lesson, yet all character have values below 22 wpm in the last lessen some are drastically different, some are close. In my understanding if i average all characters I should get to the wpm of the lesson.

**Comment by aradzie** [comment]
@owenpaulmeyer 
I made a change recently to improve the handling of accented characters, such as À, È, etc.
I think I made a logical error in that change.
Since then I deployed a new version which I hope fixed your problem.
Can you please test it again and give your feedback?

**Comment by aradzie** [comment]
@Finnitio Few reasons can influence the typing speed of a key.
1.  We smooth the speed values by passing them through a filter.
2. We exclude characters with errors from the stats. When we compute typing speed of a key, we include only those occurrences that were typed correctly.

**Comment by owenpaulmeyer** [comment]
@aradzie Hi. After a quick check, the issue seems to be resolved. Thank you!
