### ISSUE TITLE
How to build on windows

### ISSUE THREAD

**Issue by AFreeBaldy** [aradzie/keybr.com#31]
I want to help with the repo, but there doesn't seem to be any docs on how to build on windows. This repo seems very platform specific. I also keep getting webpack errors saying there are loaders for files, specifically mp3 wav and font files

**Comment by aradzie** [comment]
I am afraid it requires some work to port this project to Windows.

Maybe you can use [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/about)

**Comment by AFreeBaldy** [comment]
Thank you finally got it to build using wsl. Had to do a bit of tweaking though
