### ISSUE TITLE
[Enhancement] Allow entering a color value while creating a custom theme

### ISSUE THREAD

**Issue by guspimentel** [aradzie/keybr.com#311]
Greetings!

I love that we can create custom themes to match our preferences! For more precise tuning, it would be fantastic to have an option to enter exact color values in the picker—such as HEX, RGBA, or HSL. It would also be helpful to allow alpha values for setting opacity.

Current color picker
![image](https://github.com/user-attachments/assets/244e52cf-52af-45de-a6a9-d9ea0cdf5c54)

**Comment by aradzie** [comment]
Done,
![image](https://github.com/user-attachments/assets/67e0cb2e-d7ec-4cb5-8f15-3ff1f51dca7d)
The input field accepts HEX, rgb(r,g,b), hsl(h,s,l), etc.
