### ISSUE TITLE
Add "Arad" Farsi/Arabic font

### ISSUE THREAD

**Issue by alr86** [aradzie/keybr.com#316]
https://github.com/MDarvishi5124/Arad

Publisher says: Arad is an open source font, which is the continuation of the Shabnam font project. Arad is designed in 8 weights and four dots style and supports Farsi, Arabic, Kurdish, Turkish, Urdu and Mazerouni languages. Kanit font is used for English letters and some small changes have been made on its structure.

**Comment by Morteza-NW** [comment]
Yes, as one of the Iranian users who use this amazing site every day, I suggest this font for Persian and Arabic languages. It is hard to read and type with the default font. Also, why are there Arabic words inside the Persian text? I know we have many similarities, but we don’t use the word "al" before our words. This is one of the problems that bothers me a lot.

**Comment by aradzie** [comment]
I added the Arad font to the app.
Can you please check it, is everything working as expected?

**Comment by alr86** [comment]
Thank you, it works fine👌

**Comment by Morteza-NW** [comment]
nice, i just surprised when i opened the site 😁
