### ISSUE TITLE
multiplayer not working

### ISSUE THREAD

**Issue by lijiaju686** [aradzie/keybr.com#319]
After I deployed keybr on the server, why did multiplayer fail to connect to the server? 
This is the address       http://47.95.193.35:3000/multiplayer

**Comment by aradzie** [comment]
I have no idea. What is your server setup, do you use a reverse proxy? Can you share logs? Any more additional information

**Comment by lijiaju686** [comment]
![1731893565355](https://github.com/user-attachments/assets/e94ffb79-bb67-4c86-b7e9-55a314442616)

**Comment by aradzie** [comment]
Sorry, I still have no idea, and I cannot provide you with technical support here.
