### ISSUE TITLE
Add Noted layout for English

### ISSUE THREAD

**Issue by kayman-mk** [aradzie/keybr.com#327]
Hi,

I recently switched to [Noted](https://dariogoetz.github.io/noted-layout/index.html) and used this training program to improve my skills. Good job!

Any chance to make the Noted layout available for English too? It has been optimized for English and German but can be selected for German only. I could try to propose a PR.

Cheers,
Matthias

**Comment by aradzie** [comment]
You can now fix different languages and layouts.
