### ISSUE TITLE
I encountered some problems when deploying. 

### ISSUE THREAD

**Issue by lijiaju686** [aradzie/keybr.com#329]
Hello，
I really  like this website , but I encountered some problems when deploying it on the server
My location is Beijing, China
The environment is Ubuntu 20.04.6
Node is v20.18.0
After deployment, it is accessed via http. The typing function can be used normally, but the login and multiplayer games can't be used normally

When logging in using email, I encountered the following error

front-end error log
![image](https://github.com/user-attachments/assets/e341484c-6a6d-4cd0-bf5c-aa4bd58d19f4)
![image](https://github.com/user-attachments/assets/b2fa1255-6237-41bb-a98d-d2d20628fe29)

backed server error log
![email_log](https://github.com/user-attachments/assets/4ff75e01-a186-43f8-9f5c-d925c5b39bac)

I have some questions 

1.Is it related to my protocol? I am currently using the http protocol
2.I read this document **getting_started.md**  when I was deploying. Am I missing any operations?

Could you please help me

**Comment by aradzie** [comment]
I think you have outdated dependencies in the node_modules directory.

Try the following:

1. Delete directory `node_modules`
2. Run `npm install`. This should recompile the `better-sqlite3` module from scratch.
