### ISSUE TITLE
'Buy a Premium Account' button not working

### ISSUE THREAD

**Issue by shreyashguptas** [aradzie/keybr.com#340]
![Screenshot 2024-12-01 at 9 23 55 AM](https://github.com/user-attachments/assets/ca0fdd7e-1fba-4ea9-9517-ded96cf5fa3e)

**Comment by aradzie** [comment]
Yes, the website was under review and was waiting for approval from paddle.com.
Recently I received a confirmation that the website was approved.

**Comment by shreyashguptas** [comment]
Thanks @aradzie
