### ISSUE TITLE
Could not find '/home/eric/keybr.com/packages/keybr-intl/lib/**/*.test.{ts,tsx}'

### ISSUE THREAD

**Issue by baicaofa** [aradzie/keybr.com#341]
env DATABASE_CLIENT=sqlite npm test

got the following results

`eric@DESKTOP-RDC47JS:~/keybr.com$ env DATABASE_CLIENT=sqlite npm test

> keybr.com@0.0.0 test
> lage test --no-cache

lage - Version 2.11.15 - 20 Workers
[23:33:51] ✗ failed    @keybr/intl - test  (366ms)
[23:33:51] ? aborted   @keybr/binary - test  
[23:33:51] ? aborted   @keybr/lang - test  
[23:33:51] ? aborted   @keybr/logger - test  
[23:33:51] ? aborted   @keybr/math - test  
[23:33:51] ? aborted   @keybr/oauth - test  
[23:33:51] ? aborted   @keybr/rand - test  
[23:33:51] ? aborted   @keybr/unicode - test  

──┤ Waiting: 0 ├──┤ Completed: 8 / 8 (100%) ├──

Summary
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
@keybr/devenv - test pending, took 0.00s, queued for 0.00s
@keybr/assets - test pending, took 0.00s, queued for 0.00s
@keybr/binary - test running - incomplete, took 0.00s, queued for 0.00s
@keybr/chart - test pending, took 0.00s, queued for 0.00s
@keybr/code - test pending, took 0.00s, queued for 0.00s
@keybr/color - test pending, took 0.00s, queued for 0.00s
@keybr/config - test pending, took 0.00s, queued for 0.00s
@keybr/content - test pending, took 0.00s, queued for 0.00s
@keybr/content-books - test pending, took 0.00s, queued for 0.00s
@keybr/content-quotes - test pending, took 0.00s, queued for 0.00s
@keybr/content-words - test pending, took 0.00s, queued for 0.00s
@keybr/database - test pending, took 0.00s, queued for 0.00s
@keybr/debug - test pending, took 0.00s, queued for 0.00s
@keybr/generators - test pending, took 0.00s, queued for 0.00s
@keybr/highscores - test pending, took 0.00s, queued for 0.00s
@keybr/identicon - test pending, took 0.00s, queued for 0.00s
@keybr/intl - test failed, took 0.37s, queued for 0.01s
@keybr/keyboard - test pending, took 0.00s, queued for 0.00s
@keybr/keyboard-io - test pending, took 0.00s, queued for 0.00s
@keybr/keyboard-ui - test pending, took 0.00s, queued for 0.00s
@keybr/lang - test running - incomplete, took 0.00s, queued for 0.01s
@keybr/lesson - test pending, took 0.00s, queued for 0.00s
@keybr/lesson-loader - test pending, took 0.00s, queued for 0.00s
@keybr/lesson-ui - test pending, took 0.00s, queued for 0.00s
@keybr/logger - test running - incomplete, took 0.00s, queued for 0.01s
@keybr/math - test running - incomplete, took 0.00s, queued for 0.01s
@keybr/multiplayer-server - test pending, took 0.00s, queued for 0.00s
@keybr/multiplayer-shared - test pending, took 0.00s, queued for 0.00s
@keybr/multiplayer-ui - test pending, took 0.00s, queued for 0.00s
@keybr/names - test pending, took 0.00s, queued for 0.00s
@keybr/oauth - test running - incomplete, took 0.00s, queued for 0.01s
@keybr/pages-browser - test pending, took 0.00s, queued for 0.00s
@keybr/pages-server - test pending, took 0.00s, queued for 0.00s
@keybr/pages-shared - test pending, took 0.00s, queued for 0.00s
@keybr/phonetic-model - test pending, took 0.00s, queued for 0.00s
@keybr/phonetic-model-loader - test pending, took 0.00s, queued for 0.00s
@keybr/publicid - test pending, took 0.00s, queued for 0.00s
@keybr/rand - test running - incomplete, took 0.00s, queued for 0.01s
@keybr/result - test pending, took 0.00s, queued for 0.00s
@keybr/result-io - test pending, took 0.00s, queued for 0.00s
@keybr/result-loader - test pending, took 0.00s, queued for 0.00s
@keybr/result-userdata - test pending, took 0.00s, queued for 0.00s
@keybr/settings - test pending, took 0.00s, queued for 0.00s
@keybr/settings-database - test pending, took 0.00s, queued for 0.00s
@keybr/settings-loader - test pending, took 0.00s, queued for 0.00s
@keybr/textinput - test pending, took 0.00s, queued for 0.00s
@keybr/textinput-events - test pending, took 0.00s, queued for 0.00s
@keybr/textinput-sounds - test pending, took 0.00s, queued for 0.00s
@keybr/textinput-ui - test pending, took 0.00s, queued for 0.00s
@keybr/theme-designer - test pending, took 0.00s, queued for 0.00s
@keybr/themes - test pending, took 0.00s, queued for 0.00s
@keybr/unicode - test running - incomplete, took 0.00s, queued for 0.01s
@keybr/widget - test pending, took 0.00s, queued for 0.00s
@keybr/page-account - test pending, took 0.00s, queued for 0.00s
@keybr/page-help - test pending, took 0.00s, queued for 0.00s
@keybr/page-highscores - test pending, took 0.00s, queued for 0.00s
@keybr/page-layouts - test pending, took 0.00s, queued for 0.00s
@keybr/page-multiplayer - test pending, took 0.00s, queued for 0.00s
@keybr/page-practice - test pending, took 0.00s, queued for 0.00s
@keybr/page-profile - test pending, took 0.00s, queued for 0.00s
@keybr/page-static - test pending, took 0.00s, queued for 0.00s
@keybr/page-typing-test - test pending, took 0.00s, queued for 0.00s
@keybr/server - test pending, took 0.00s, queued for 0.00s
@keybr/server-cli - test pending, took 0.00s, queued for 0.00s
success: 0, skipped: 8, pending: 56, aborted: 0, failed: 1
worker restarts: 0, max worker memory usage: 0.00 MB
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
[@keybr/intl test] ERROR DETECTED

Running npm run test, pid: 14330

> @keybr/intl@0.0.0 test
> tstest --import=@keybr/test-env-browser --import=@keybr/test-env-bundler --test 'lib/**/*.test.{ts,tsx}'

Could not find '/home/eric/keybr.com/packages/keybr-intl/lib/**/*.test.{ts,tsx}'
npm error Lifecycle script `test` failed with error:
npm error code 1
npm error path /home/eric/keybr.com/packages/keybr-intl
npm error workspace @keybr/intl@0.0.0
npm error location /home/eric/keybr.com/packages/keybr-intl
npm error command failed
npm error command sh -c tstest --import=@keybr/test-env-browser --import=@keybr/test-env-bundler --test 'lib/**/*.test.{ts,tsx}'
[object Object]

┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
Took a total of 0.37s to complete. `

**Comment by aradzie** [comment]
What is your nodejs version? 
As far as I remember, glob on node 20 is broken.
It should work on node 22.

**Comment by aradzie** [comment]
Here is a Node.js 20 bug about glob not working: https://github.com/nodejs/node/issues/50658
