### ISSUE TITLE
[feature req] Please add ( ) { } [ ] \ + =  the characters . Will be helpful for programmer

### ISSUE THREAD

**Issue by Saibalweb** [aradzie/keybr.com#37]
I  have been using this website more than years. I improved  my typing speed quite lot . 
I searched the settings and added the punctuation characters but these ( ) { } [ ] \ + characters didn't showed .  
It will be helpful if you add those extra characters. Those are extremely common words for programmer .
You can add a separate section in setting!

![image](https://github.com/aradzie/keybr.com/assets/106599241/2776ae53-b9ad-424f-85ce-62d35c499add)

**Comment by yash-fn** [comment]
this would be totally awesome

**Comment by aradzie** [comment]
Just an hour ago I added the ability to show stats of the special characters.

![image](https://github.com/aradzie/keybr.com/assets/44386/d54dd32c-d255-49a2-905a-5ded96314e3d)

This is not a full solution yet but a step in that direction.

**Comment by deberle** [comment]
Support for training special characters is my most requested feature in this awesome tool!

**Comment by sedounet** [comment]
+1 for beginer would be fantastic!!!!

**Comment by nottud** [comment]
This is a must have feature for me. I am learning for programming and it is frustrating they are not included. Might be helpful if you can specify what symbols to include. I am looking at web stuff recently so also want @,  <,  >, and = including as well which is not on your list.

**Comment by drewkill32** [comment]
any update on this? this is my worst typing speed at the moment

**Comment by babymedia** [comment]
Kindly add these punctuation characters  ( ) { } [ ] \ += they will help us practice programming.

**Comment by aradzie** [comment]
So we have a new lesson type, `"Source Code"`.

![image](https://github.com/aradzie/keybr.com/assets/44386/f4899b7e-5f78-47c7-9eb0-a11e86c0056e)

It generates nonsensical but syntactically correct fragments of source code. For now we have can generate HTML, CSS and C++. More languages to come.

**Comment by aradzie** [comment]
It is just a beginning. I see a few ways to improve this features.

For start we can implement syntax highlighting to make it easier to read the generated code fragments.

Also, we can gradually unlock the punctuation characters and generate code fragments with the unlocked characters only.

**Comment by marekbrze** [comment]
It would be also great to have a variant of the numbers lessons with special characters. So basically lesson that mixes numbers and numbers with shift. 

Currently I struggle to learn those. Coding lessons are great, but focused practice of the special numbers in the numbers row would be awesome
