### ISSUE TITLE
feature: require all keys above threshold to unlock the next key

### ISSUE THREAD

**Issue by aradzie** [aradzie/keybr.com#44]
It is a typical situation that when a user unlocks and focuses on a new key, all the previously unlocked keys suffer. 
Let's say we are going from R to L. As we learn L, the speed of R will likely drop.

Add a new option that requires users to pass the speed threshold for all previously unlocked keys before a new key is unlocked.

Example scenario.
A user successfully unlocked E,I,N,T,R and the focus is on key L.
User works on L, and in the process the speed of E,I,N,T,R drop below the threshold.
User passed the speed threshold for L, however the new key is not unlocked.
Instead, the algorithm focuses on one of E,I,N,T,R until the user recovers their speed.

**Comment by havarhagelund** [comment]
+ 1

**Comment by Nullarity** [comment]
From my point of view, this algorithm makes it inadequately difficult to open letters with the setting of 300+ CPM.
