### ISSUE TITLE
[Feature request] colour coded keyboard

### ISSUE THREAD

**Issue by alfzki** [aradzie/keybr.com#52]
Sometimes I forgot which finger is used to press key like: "c", "y", "r". Would be helpful to have optional colour on virtual keyboard. 
![image](https://github.com/aradzie/keybr.com/assets/80497464/b4d8e010-5434-43e6-b682-148dfa36979b)

**Comment by xuan-nguyen-swe** [comment]
I would like to teach my kid (5 years old) and color is very important in this case.

**Comment by xuan-nguyen-swe** [comment]
[This site](https://agilefingers.com/lessons/lesson-fingers-little-row-1) even changes the position of the overlayed hands too.

![image](https://github.com/aradzie/keybr.com/assets/24372782/677acf92-ee46-4b9e-b681-b4bcaf60a66e)

**Comment by aradzie** [comment]
done in #57

**Comment by xuan-nguyen-swe** [comment]
wow, really fast!!! Thanks!
