### ISSUE TITLE
keybr.com site should show a link to the tag or commit hash

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [aradzie/keybr.com#58]
The webpage keybr.com should show a link to the tag or commit hash, which was used to deploy to keybr.com.
So that users know which features are expected and which features are not yet available.
I think it could be next to the GitHub link or in a subpage like Help page.

**Comment by aradzie** [comment]
I can print a commit hash to the browser console.

**Comment by xuan-nguyen-swe** [comment]
> I can print a commit hash to the browser console.

I think that's a great idea, because it doesn't require effort to integrate with the CI/CD.
