### ISSUE TITLE
feature: add matrix keyboard view

### ISSUE THREAD

**Issue by MrRTi** [aradzie/keybr.com#61]
add matrix keyboard view as additional view to be selected instead classic view
<img width="715" alt="image" src="https://github.com/aradzie/keybr.com/assets/38328305/c0caacc3-91a0-41d3-8aff-035648de5ca8">

example for matrix keyboard view with colemak (picture from https://colemakmods.github.io/mod-dh/keyboards.html)
![image](https://github.com/aradzie/keybr.com/assets/38328305/310d68f9-352f-438e-8c40-bfed12e94620)

**Comment by aradzie** [comment]
![image](https://github.com/aradzie/keybr.com/assets/44386/d52cc1ce-5cf6-48ac-b8bd-0f7dc7a7fd6e)

Done in 09f736a0c35ff94e8d33d0fc717c5eef5ff3e728

**Comment by MrRTi** [comment]
Awesome, thank you!
