### ISSUE TITLE
Bug: Enter key no longer moves to a new line

### ISSUE THREAD

**Issue by mateuszduda** [aradzie/keybr.com#66]
Previously, when reaching the end of a line, either Space or Enter would move the cursor to a new line. Now only Space works, while Enter is treated as an error. I noticed this after the colored keyboard layout was introduced.

![image](https://github.com/aradzie/keybr.com/assets/5666134/93a43d6a-aeea-40f1-aa5f-f004585e7593)

**Comment by aradzie** [comment]
I think I've fixed this issue in bb445f7ce184689967ba64c42b80eeab8181b260
