### ISSUE TITLE
Feature Request: Toggle Option for Displaying Spaces as Dots

### ISSUE THREAD

**Issue by moHaHa** [aradzie/keybr.com#68]
**Description:**
I would like to request a new feature for the keyboard learning website that allows users to toggle the display of spaces as dots. Currently, the website displays spaces as dots, which is helpful for learning, but it would be great if users could choose whether to show spaces as dots or retain the traditional space character.

Dots enabled
![image](https://github.com/aradzie/keybr.com/assets/72744132/3651cf0a-2f0d-4427-bdb4-fe2889d8d1c1)

Dots disabled
![image](https://github.com/aradzie/keybr.com/assets/72744132/1971d6ed-21a2-4e24-bd74-8b47eb45bfd5)

 

**User Story:**
As a user of the keyboard learning website, I want the option to toggle the display of spaces as dots on and off. This would allow me to customize my learning experience according to my preferences.

**Proposed Implementation:**
1. Create a new section in the user preferences/settings page to control the display of spaces.
2. Add a checkbox or toggle switch labeled "Display Spaces as Dots" in the settings.
3. When the option is enabled, spaces are displayed as dots, similar to the current behavior.
4. When the option is disabled, spaces are displayed as regular space characters.

**Benefits:**
1. Improved user customization and personalization of the learning experience.
2. Users can choose the display style that suits their preferences.
3. This feature could make the website more inclusive for users with varying needs.

**Additional Information:**
Please consider adding this feature as an optional customization for users to enhance their experience on the website.

Thank you for your consideration.

**Comment by MrRTi** [comment]
Are you talking about this setting which is at settings page? And I think it was there for several months
<img width="889" alt="image" src="https://github.com/aradzie/keybr.com/assets/38328305/801d8418-daa6-40c2-a6ba-378cd6305aca">
