### ISSUE TITLE
Some letter exercises lack variety

### ISSUE THREAD

**Issue by sanchopanca** [aradzie/keybr.com#75]
In particular, exercises for the Russian letter `ё` appear to only have two words and their variations
![Selection_067](https://github.com/aradzie/keybr.com/assets/1524093/b6bb9266-be77-4fb6-970e-41fe5fc9f21a)
It's not clear why is this the case. The `words-ru.json` file contains 22 different words that include the letter `ё` and none of them is one of those two on the screenshot, so I'm not sure what is the source of the words in the exercises.

**Comment by aradzie** [comment]
I think the letter ё is special in Russian. It might be that the text we used to generate the phonetic model did not have too many such letters.

I might need to re-create the phonetic model from another corpus of text.

**Comment by sanchopanca** [comment]
It's true that it's somewhat special. The tricky part is that, depending on the style of the text, all `ё` can be written as `е`.

According to [wiktionary](https://ru.wiktionary.org/wiki/%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5:%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D1%87%D0%B0%D1%81%D1%82%D0%BE%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%BF%D0%BE_%D0%9D%D0%9A%D0%A0%D0%AF), the two most frequent russian words with a `ё` are `ещё` and `её`. Thus if they are in the text, it is probably written in the style with `ё` written out.

But, I guess, simply checking if there is any `ё` in the text is sufficient.

**Comment by aradzie** [comment]
It is quite difficult to find a corpus of Russian text with consistent usage of the letter `ё`.

I found a good [frequency dictionary](http://dict.ruslang.ru/freq.php), unfortunately it does not have that letter at all, so don't we.

So, we  "solved" this bug by getting rid of the letter `ё`.
