### ISSUE TITLE
I got a database error for the third time

### ISSUE THREAD

**Issue by PrathamVerma999** [aradzie/keybr.com#76]
![image](https://github.com/aradzie/keybr.com/assets/110521546/a5e27069-167f-4d78-a4be-15d1344e2b87)

**Comment by nicholasrq** [comment]
+1

**Comment by JBarmentlo** [comment]
Same here got a few in half an hour.
```
Error

Oh no, something bad has happened!

DatabaseError: Cannot add records to database (type=[object DatabaseError])
Ne@https://www.keybr.com/assets/84184e8bb5e76d1d.js:1:27461
append@https://www.keybr.com/assets/84184e8bb5e76d1d.js:1:79355


Cause: TypeError: Network error
9623/l/b/v.onerror@https://www.keybr.com/assets/c5ad3464f4d6914d.js:2:3891
```

**Comment by aradzie** [comment]
> ![image](https://user-images.githubusercontent.com/110521546/278852351-a5e27069-167f-4d78-a4be-15d1344e2b87.png)

Hmm, these errors can mean anything.

Can you please elaborate, what is your browser/OS?

Do you have multiple tabs with keybr open?

Are you browsing in the private mode?

**Comment by nicholasrq** [comment]
for me it's only one tab

macOS Sonoma / Arc Browser (latest)

**Comment by aradzie** [comment]
> Arc Browser

Oh that's interesting, a new browser to test ;) Seriously speaking, Arc Browser is based on Chromium, so I believe it is fully compatible.

How often can you reproduce this error? Is it every time or time to time?

Is there anything interesting in the dev tools console?

**Comment by aradzie** [comment]
Nobody complained about this issue for a very long time, so I am assume it is stale and can be closed.
I believe the cause was somewhere on the hosting side, or maybe in Cloudflare.
