### ISSUE TITLE
Bug: Backspace doesn't work anymore

### ISSUE THREAD

**Issue by deberle** [aradzie/keybr.com#77]
- uncheck "Stop cursor on error"
- type a wrong key 
- type backspace to go back 
=> nothing happens.

Possibly related to bb445f7ce184689967ba64c42b80eeab8181b260

**Comment by aradzie** [comment]
Ah, I see. This bug is reproducible in Safari.

**Comment by vladpi** [comment]
Hi! 
Faced the same problem in Safari. But at the same time, the first click on the backspace is triggered, and the subsequent ones are not.

Safari 17.0 (19616.1.27.211.1)

**Comment by Nikscorp** [comment]
Same for me in Safari 15.6.1. Only first backspace click is working

**Comment by aradzie** [comment]
I thought I'll take me half an hour to add a simple feature. Instead I spent multiple hours catching browser compatibility bugs. 
I am sorry for the inconvenience, the new version with the bug fix is already online.

**Comment by deberle** [comment]
Thanks a lot, it works for me now.
