### ISSUE TITLE
sometimes words are not visible

### ISSUE THREAD

**Issue by mu-us61** [aradzie/keybr.com#80]
![image](https://github.com/aradzie/keybr.com/assets/73366454/b1456774-7999-460d-9eb8-f9d252df8efa)

sometimes bottom words are in bug

**Comment by mu-us61** [comment]
![image](https://github.com/aradzie/keybr.com/assets/73366454/5785a4c7-76ff-4f03-99e4-c71fb1d53ee7)

I use debian 12 with chrome , here height is 384px but the content is more so it doesnt show last line, disabling keyboard or stats is not a workaround still last line sometimes doesnt show , not always happens but sometimes

**Comment by aradzie** [comment]
> ![image](https://user-images.githubusercontent.com/73366454/280547848-5785a4c7-76ff-4f03-99e4-c71fb1d53ee7.png)
> 
> I use debian 12 with chrome , here height is 384px but the content is more so it doesnt show last line, disabling keyboard or stats is not a workaround still last line sometimes doesnt show , not always happens but sometimes

This is a new feature. To relieve the browser from making layout changes after each text update, we measure the text dimensions and explicitly set the text container size. It should make typing slightly more responsive.
I tested it in Chrome, Firefox and Safari. Linux, Windows and macOS, it seemed to work just fine everywhere.

Can you please clarify, do you encounter this issue every time or from time to time?

**Comment by mu-us61** [comment]
it happens time to time , sometimes bottom line words's tips are visible sometimes are not , for example for those 2 screenshot both of them had same issue

**Comment by mu-us61** [comment]
![image](https://github.com/aradzie/keybr.com/assets/73366454/d72d2559-ec33-4e2c-b94a-64b9e6da7a6b)
***
happened again, 
***
![image](https://github.com/aradzie/keybr.com/assets/73366454/0d3f72dd-61e6-4305-88b6-04511d1a3c59)
***
can it be because spans has  margin 0.5 rem ? maybe

**Comment by mu-us61** [comment]
![Screenshot_20231106_185202](https://github.com/aradzie/keybr.com/assets/73366454/7d452bea-9cfc-4817-bfd6-51c4aa25b60e)

![Screenshot_20231106_185356](https://github.com/aradzie/keybr.com/assets/73366454/f4e0a7e1-5894-4a6a-a627-f5a623923f01)

***
as a workaround when I change resolution it fixes , first pic is normal chrome on debian 12 , 15.6 inch laptop, 1920*1080

**Comment by garis** [comment]
I noticed the same thing starting from today.
![image](https://github.com/aradzie/keybr.com/assets/13544227/ee7d37a1-11e7-4037-b640-7f10fb916e67)

If I change the layout then the last words are visible but sometimes they are not in the third interface layout (I am not sure if this workaround works always or not).
![image](https://github.com/aradzie/keybr.com/assets/13544227/8b5b59f9-92cc-43e8-a3ea-9c15a57c09d6)

**Comment by aradzie** [comment]
Bugs like these are difficult to fix. I've made an attempt in 2050590a446abb01413ee6fe33decf4c6f6d8e2d , maybe it will help.
Can you please test it and say if the issue still exists?

**Comment by mu-us61** [comment]
![Peek 2023-11-09 21-00](https://github.com/aradzie/keybr.com/assets/73366454/05cbf95e-bac6-47ec-8043-c1cd15fc18fc)

***
yes still exists , who_keep_ver those are last words but the last one did not show up
