### ISSUE TITLE
feature: unlocking keys in the keyboard order

### ISSUE THREAD

**Issue by aradzie** [aradzie/keybr.com#84]
In the guided mode we sort keys with the decreasing frequency order. 
Consider another possibility, sorting the keys in such a way that the home row comes first, then the top row, then the bottom row.
This might not work for Qwerty. However, it should work for Drorak, Colemak.

**Comment by trapicki** [comment]
What I find so unique with keybr is the learning order by frequency. This is a natural order, allows you to learn the most important keys first, and last not least rewards you with being able to write sensible words very quick - no dfjk any more.

So please don't. Don't even allow for braindead homerow hammering of stupid artifically crafted words.

**Comment by aradzie** [comment]
Don't worry, this will be a configuration option, disabled by default.
I have tested it myself, and it works really well with the optimized layouts, like Dvorak, Colemak, Bepo, etc.
While it is true that these layouts have most frequent letters on the home row, there are exceptions.
