### ISSUE TITLE
Typing speed chart is incorrect

### ISSUE THREAD

**Issue by dmikhalin** [aradzie/keybr.com#85]
The number of keys in the lesson should be monotonically non-decreasing, regardless of the selected smoothness level, but this isn't the case. On some smoothness values it can decrease dramatically, by approx. 5 keys. Could it be that three data rows are using the same `filter` object for smoothing, thereby influencing each other?

<img width="789" alt="Screenshot 2023-11-11 20 24 32" src="https://github.com/aradzie/keybr.com/assets/17214250/fb5908c9-50c0-4812-8b94-b0800b0408cc">

**Comment by aradzie** [comment]
Various factors can influence the number of letters/keys:

1. You can adjust the "_Unlock more letters_" slider on the settings page to increase or decrease the number of letters/keys.
2. You can switch, for example, to the _Custom words_ mode, which effectively "unlocks" all letters/keys, and then go back to the _Guided lessons_ mode, which again can decrease that number.

At one point I thought that this statistic, the number of keys, has no noise and should not be smoothed. Then people started complaining and I had to revert the change ;)

Please note that we merge the results from all lesson types into that graph. I believe it makes sense. No matter how you practice, your typing speed is not changing in isolation.

This issue made me thinking. There are a couple of ways to improve this graph.

1. We can add a filter for different lesson types, or even better
2. We can highlight different lesson types on the graph

The latter can be done, for example, by painting vertical bands of different colors in the background, where the band color indicates a lesson type.

**Comment by dmikhalin** [comment]
> 1. You can adjust the "_Unlock more letters_" slider on the settings page to increase or decrease the number of letters/keys.
> 2. You can switch, for example, to the _Custom words_ mode, which effectively "unlocks" all letters/keys, and then go back to the _Guided lessons_ mode, which again can decrease that number.

Haven't used these options.

> Please note that we merge the results from all lesson types into that graph. I believe it makes sense. No matter how you practice, your typing speed is not changing in isolation.

Hmm. I used Typing test several times. Is the number of keys more than 26 in that type of lesson? Do you count capital letters or punctuation characters as keys?

**Comment by aradzie** [comment]
This is another graph from your profile:

![image](https://github.com/aradzie/keybr.com/assets/44386/ebf84f1f-ba33-4b69-91d2-5caa68e8aa25)

We can see discontinuities on the horizontal bars there. It means letters disappear from the lessons.

If we take a vertical slice on this graph, count the number of letters in the slice, it roughly correspond to the number of letters on the Typing Speed graph.

As of why letters disappear, I have another theory. Some letters are so rare, that when the algorithm shifts focus away from such a letter, it almost never appears in the latter lessons.

However, let me take a closer look at your data.

**Comment by dmikhalin** [comment]
I see, it explains my misunderstanding. Of course, the probability of absence of some characters in such a small lesson is pretty big. Thanks!

**Comment by aradzie** [comment]
Again, I don't see any obvious bug in the code.

But the disappearance of letters made me curious. I have never paid attention to this before. So I wrote a simple [script](https://github.com/aradzie/keybr.com/commit/dd2954a1e29fa6ff7558409960c8255658c6c43a) to gather some statistics, and here is the result:

```
unique letter count with no filter 22.77
unique letter count when focusing on E 23.23
unique letter count when focusing on N 22.67
unique letter count when focusing on I 23.68
unique letter count when focusing on T 22.02
unique letter count when focusing on R 21.55
unique letter count when focusing on L 22.64
unique letter count when focusing on S 22.16
unique letter count when focusing on A 23.67
unique letter count when focusing on U 22.81
unique letter count when focusing on O 22.33
unique letter count when focusing on D 20.68
unique letter count when focusing on Y 21.09
unique letter count when focusing on C 21.98
unique letter count when focusing on H 22.34
unique letter count when focusing on G 19.56
unique letter count when focusing on M 21.25
unique letter count when focusing on P 21.53
unique letter count when focusing on B 21.84
unique letter count when focusing on K 19.44
unique letter count when focusing on V 20.36
unique letter count when focusing on W 21.55
unique letter count when focusing on F 20.12
unique letter count when focusing on Z 16.82
unique letter count when focusing on X 20.72
unique letter count when focusing on Q 19.49
unique letter count when focusing on J 17.26
```

The letters above are sorted in the order of decreasing frequency. It can be seen that when there is no focus on a letter, then the average number of unique letters that are appearing in the words is 22.77. However, as we shift focus to the least frequent letters, the variety of unique letters is decreasing. For example, when we force the letter Z, then the number of unique letters is only 16.82.

**Comment by dmikhalin** [comment]
I suppose that some rear letters like Q appears only together with some other letters. E.g., if Q is the first letter, then probably the next letter is U, and then, I guess, A, E or U. So, if we are randomly choosing a word with Q, the probability of appearing of some letters is pretty small.

**Comment by dmikhalin** [comment]
If we look at all words with the letter Q then the average quantity of letters in one word is the following:

U: 1.24
E: 1.11
I: 1.06
Q: 1.0
A: 0.871
N: 0.688
S: 0.585
T: 0.571
R: 0.544
L: 0.507
O: 0.427
C: 0.251
D: 0.239
Y: 0.159
M: 0.15
B: 0.123
P: 0.116
H: 0.09
G: 0.0766
V: 0.0656
F: 0.0592
Z: 0.0396
K: 0.0394
X: 0.0169
W: 0.0142
J: 0.00964
