### ISSUE TITLE
Backtracking

### ISSUE THREAD

**Issue by mister-choo** [aradzie/keybr.com#87]
It seems that now when option "Unlock a next key only when
The previous keys are also above the target speed' Is enabled. Keys get locked again if one of the previous keys falls below the threshold. 
I see this behavior as undesirable, because it is the presence of a new key makes others fall. But here I end up in a loop, where I unlock a new key -> one of the previous falls -> i repratice them without a new key -> new key unlocks -> it happens again

**Comment by eikowagenknecht** [comment]
I noticed the same. Would be nice if unlocked keys stayed unlocked.

**Comment by pratik-mahamuni** [comment]
The feature should keep the new key and not unlock the next one until all of the unlocked keys are above the threshold.
