### ISSUE TITLE
while typing when we delay for 3 4 seconds it again starts from beginning of line

### ISSUE THREAD

**Issue by DeepakQuazma123** [aradzie/keybr.com#96]
when we delay typing for about 3 to 4 seconds the cursor moves to the beginning of the line.

**Comment by haynesgt** [comment]
yeah it's frustrating that it resets so quickly. I've been trying to learn dvorak and it can take a few seconds to find the right key.

**Comment by jenden0** [comment]
This is also problematic for kids. Even when they know the positions they easily get distracted, and with the current 5 second timeout it's hard for them to make it through an entire chunk. And where an adult may realize what happened and try to be a bit more careful, to a kid it can seem pretty arbitrary and demotivating. Would love to see this customizable as I think the idea is sound, but some people are just going to need more time for some reason or another.

**Comment by Shinechaote** [comment]
A setting to turn this off or increase the time would indeed be very nice

**Comment by aradzie** [comment]
I have increased the timeout.

Also, I added a visual pointer to the next key to make it easier to find it:

![image](https://github.com/aradzie/keybr.com/assets/44386/5e281e60-81dc-4763-b0d3-ba7c43d1dfbf)

**Comment by ZweiEuro** [comment]
Is there a possibility to turn this off? @aradzie 
I am trying to get to grips with a moergo keyboard and a custom layout so the indicators are of no help to me and it takes me a good while to find the right key and layer
